// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package storedb

import (
	"context"
	"time"
)

const deleteDeployTarget = `-- name: DeleteDeployTarget :execrows
DELETE FROM deploy_targets
WHERE id = ? AND cert_id = ?
`

type DeleteDeployTargetParams struct {
	ID     string
	CertID string
}

func (q *Queries) DeleteDeployTarget(ctx context.Context, arg DeleteDeployTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeployTarget, arg.ID, arg.CertID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT id, cert_id, name,
       cert_path, key_path, chain_path,
       mode, owner, "group",
       post_command, auto_on_rotate,
       last_deployed_at, last_deployed_serial,
       last_status, last_error, created_at
FROM deploy_targets
WHERE id = ?
`

func (q *Queries) GetDeployTarget(ctx context.Context, id string) (DeployTarget, error) {
	row := q.db.QueryRowContext(ctx, getDeployTarget, id)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.Name,
		&i.CertPath,
		&i.KeyPath,
		&i.ChainPath,
		&i.Mode,
		&i.Owner,
		&i.Group,
		&i.PostCommand,
		&i.AutoOnRotate,
		&i.LastDeployedAt,
		&i.LastDeployedSerial,
		&i.LastStatus,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeployTarget = `-- name: InsertDeployTarget :exec

INSERT INTO deploy_targets (
    id, cert_id, name,
    cert_path, key_path, chain_path,
    mode, owner, "group",
    post_command, auto_on_rotate
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeployTargetParams struct {
	ID           string
	CertID       string
	Name         string
	CertPath     string
	KeyPath      string
	ChainPath    *string
	Mode         string
	Owner        *string
	Group        *string
	PostCommand  *string
	AutoOnRotate int64
}

// Queries against the deploy_targets table. Backs internal/store/deploys.go.
func (q *Queries) InsertDeployTarget(ctx context.Context, arg InsertDeployTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertDeployTarget,
		arg.ID,
		arg.CertID,
		arg.Name,
		arg.CertPath,
		arg.KeyPath,
		arg.ChainPath,
		arg.Mode,
		arg.Owner,
		arg.Group,
		arg.PostCommand,
		arg.AutoOnRotate,
	)
	return err
}

const insertDeployTargetWithRunState = `-- name: InsertDeployTargetWithRunState :exec
INSERT INTO deploy_targets (
    id, cert_id, name,
    cert_path, key_path, chain_path,
    mode, owner, "group",
    post_command, auto_on_rotate,
    last_deployed_at, last_deployed_serial,
    last_status, last_error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeployTargetWithRunStateParams struct {
	ID                 string
	CertID             string
	Name               string
	CertPath           string
	KeyPath            string
	ChainPath          *string
	Mode               string
	Owner              *string
	Group              *string
	PostCommand        *string
	AutoOnRotate       int64
	LastDeployedAt     *time.Time
	LastDeployedSerial *string
	LastStatus         *string
	LastError          *string
}

func (q *Queries) InsertDeployTargetWithRunState(ctx context.Context, arg InsertDeployTargetWithRunStateParams) error {
	_, err := q.db.ExecContext(ctx, insertDeployTargetWithRunState,
		arg.ID,
		arg.CertID,
		arg.Name,
		arg.CertPath,
		arg.KeyPath,
		arg.ChainPath,
		arg.Mode,
		arg.Owner,
		arg.Group,
		arg.PostCommand,
		arg.AutoOnRotate,
		arg.LastDeployedAt,
		arg.LastDeployedSerial,
		arg.LastStatus,
		arg.LastError,
	)
	return err
}

const listDeployTargetsByCertID = `-- name: ListDeployTargetsByCertID :many
SELECT id, cert_id, name,
       cert_path, key_path, chain_path,
       mode, owner, "group",
       post_command, auto_on_rotate,
       last_deployed_at, last_deployed_serial,
       last_status, last_error, created_at
FROM deploy_targets
WHERE cert_id = ?
ORDER BY name, created_at
`

func (q *Queries) ListDeployTargetsByCertID(ctx context.Context, certID string) ([]DeployTarget, error) {
	rows, err := q.db.QueryContext(ctx, listDeployTargetsByCertID, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTarget{}
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.Name,
			&i.CertPath,
			&i.KeyPath,
			&i.ChainPath,
			&i.Mode,
			&i.Owner,
			&i.Group,
			&i.PostCommand,
			&i.AutoOnRotate,
			&i.LastDeployedAt,
			&i.LastDeployedSerial,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeployRun = `-- name: RecordDeployRun :execrows
UPDATE deploy_targets
   SET last_deployed_at     = ?,
       last_deployed_serial = ?,
       last_status          = ?,
       last_error           = ?
   WHERE id = ?
`

type RecordDeployRunParams struct {
	LastDeployedAt     *time.Time
	LastDeployedSerial *string
	LastStatus         *string
	LastError          *string
	ID                 string
}

func (q *Queries) RecordDeployRun(ctx context.Context, arg RecordDeployRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordDeployRun,
		arg.LastDeployedAt,
		arg.LastDeployedSerial,
		arg.LastStatus,
		arg.LastError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeployTarget = `-- name: UpdateDeployTarget :execrows
UPDATE deploy_targets
   SET name           = ?,
       cert_path      = ?,
       key_path       = ?,
       chain_path     = ?,
       mode           = ?,
       owner          = ?,
       "group"        = ?,
       post_command   = ?,
       auto_on_rotate = ?
   WHERE id = ? AND cert_id = ?
`

type UpdateDeployTargetParams struct {
	Name         string
	CertPath     string
	KeyPath      string
	ChainPath    *string
	Mode         string
	Owner        *string
	Group        *string
	PostCommand  *string
	AutoOnRotate int64
	ID           string
	CertID       string
}

func (q *Queries) UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeployTarget,
		arg.Name,
		arg.CertPath,
		arg.KeyPath,
		arg.ChainPath,
		arg.Mode,
		arg.Owner,
		arg.Group,
		arg.PostCommand,
		arg.AutoOnRotate,
		arg.ID,
		arg.CertID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
